import { AppWallet, Transaction, resolvePlutusScriptAddress, BlockfrostProvider } from '@meshsdk/core';
import * as dotenv from 'dotenv';
import * as fs from 'fs';

dotenv.config();

/**
 * Script to deploy the Aiken ZK Verifier contract to the Cardano Preprod Testnet.
 * In Cardano, "deploying" a contract typically means locking some funds at the script address
 * to make the UTxO available for future validation logic.
 */
async function deployContract() {
  console.log("Initializing deployment to Preprod Testnet...");

  // 1. Initialize the Blockfrost provider for Preprod
  const blockchainProvider = new BlockfrostProvider(
    process.env.BLOCKFROST_PROJECT_ID || 'preprod...'
  );

  // 2. Initialize the deployment wallet using a mnemonic phrase
  if (!process.env.MNEMONIC) throw new Error("Please set MNEMONIC in your .env file");
  
  const wallet = new AppWallet({
    networkId: 0, // 0 for Testnet (Preprod), 1 for Mainnet
    fetcher: blockchainProvider,
    submitter: blockchainProvider,
    key: {
      type: 'mnemonic',
      words: process.env.MNEMONIC.split(' '),
    },
  });

  const walletAddress = wallet.getPaymentAddress();
  console.log(`Deployer Wallet Address: ${walletAddress}`);

  // 3. Load the compiled Aiken contract (from plutus.json generated by `aiken build`)
  // For demonstration, we use a placeholder CBOR string.
  let scriptCbor = "4e4d01000033222220051200120011"; 
  try {
    // Normally you would read the compiled contract like this:
    // const plutusJson = JSON.parse(fs.readFileSync('../contracts/plutus.json', 'utf8'));
    // scriptCbor = plutusJson.validators[0].compiledCode;
  } catch (e) {
    console.log("Could not find plutus.json, using placeholder CBOR.");
  }

  const script = {
    code: scriptCbor,
    version: 'V3' // We use Plutus V3 to access the BLS12-381 ZK primitives
  };

  // 4. Resolve and log the verifiable contract address
  const scriptAddress = resolvePlutusScriptAddress(script, 0); // 0 = Testnet
  console.log(`✅ ZK Verifier Contract Address: ${scriptAddress}`);

  // 5. Build the deployment transaction (locking 2 ADA at the script address)
  const tx = new Transaction({ initiator: wallet })
    .sendLovelace(
      {
        address: scriptAddress,
        datum: {
          value: "deployer_public_key_hash", // Placeholder inline datum
          inline: true
        }
      },
      "2000000" // Lock 2 ADA
    );

  // 6. Sign and Submit
  console.log("Building and signing transaction...");
  const unsignedTx = await tx.build();
  const signedTx = await wallet.signTx(unsignedTx);
  
  console.log("Submitting transaction...");
  const txHash = await wallet.submitTx(signedTx);

  console.log(`🎉 Contract successfully deployed!`);
  console.log(`Transaction Hash: ${txHash}`);
}

deployContract().catch(console.error);
